###########################################################################
# Kbuild file for NVIDIA Linux GPU driver kernel modules
###########################################################################

# Ожидается, что родительский Makefile определяет:
# NV_KERNEL_SOURCES : Корень дерева исходного кода ядра.
# NV_KERNEL_OUTPUT : Дерево вывода ядра.
# NV_KERNEL_MODULES : Список модулей для сборки, разделенный пробелами.
# ARCH : Целевая архитектура процессора: x86_64|arm64|powerpc

NV_BUILD_TYPE ?= release
PLATFORM_IS_ANDROID ?= 0

# Общие флаги компиляции
EXTRA_CFLAGS += -I$(src)/common/inc -I$(src)
EXTRA_CFLAGS += -Wall -Wno-cast-qual -Wno-format-extra-args
EXTRA_CFLAGS += -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"575.51.03\"

# Платформо-специфические флаги
ifeq ($(PLATFORM_IS_ANDROID),1)
    EXTRA_CFLAGS += -DNV_FILESYSTEM_ACCESS_AVAILABLE=0
else
    EXTRA_CFLAGS += -DNV_FILESYSTEM_ACCESS_AVAILABLE=1
endif

# Проверка архитектуры и добавление соответствующих флагов
ifeq ($(ARCH),arm64)
    EXTRA_CFLAGS += -mstrict-align -march=armv8-a
endif

ifeq ($(ARCH),x86_64)
    EXTRA_CFLAGS += -mno-red-zone -mcmodel=kernel
endif

ifeq ($(ARCH),powerpc)
    EXTRA_CFLAGS += -mlittle-endian -mno-strict-align
endif

# Установка флагов для отладки
ifneq ($(NV_BUILD_TYPE),debug)
    EXTRA_CFLAGS += -Wuninitialized
else
    EXTRA_CFLAGS += -g
endif

EXTRA_CFLAGS += -fno-strict-aliasing -DNV_UVM_ENABLE
EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)

# Интеграция conftest для проверки заголовков
NV_CONFTEST_SCRIPT := $(src)/conftest.sh
NV_CONFTEST_HEADER := $(obj)/conftest/headers.h
NV_CONFTEST_CMD := /bin/sh $(NV_CONFTEST_SCRIPT) "$(CC)" $(ARCH) $(NV_KERNEL_SOURCES) $(NV_KERNEL_OUTPUT)

# Генерация заголовков для conftest
NV_CONFTEST_HEADERS := $(obj)/conftest/patches.h $(NV_CONFTEST_HEADER)

$(obj)/conftest/patches.h: $(NV_CONFTEST_SCRIPT)
    @mkdir -p $(obj)/conftest
    @$(NV_CONFTEST_CMD) patch_check > $@

# Проверка наличия заголовков
NV_HEADER_PRESENCE_TESTS = <список_заголовков_для_проверки>

# Определение правил для проверки наличия заголовков
define NV_HEADER_PRESENCE_CHECK
$(call NV_HEADER_PRESENCE_PART,$(1)): $(NV_CONFTEST_SCRIPT) $(obj)/conftest/uts_release
    @mkdir -p $(dir $@)
    @$(NV_CONFTEST_CMD) test_kernel_header '$(NV_CONFTEST_CFLAGS)' '$(1)' > $@
endef

# Оценка правил для каждого заголовка в списке
$(foreach header,$(NV_HEADER_PRESENCE_TESTS),$(eval $(call NV_HEADER_PRESENCE_CHECK,$(header))))

# Генерация заголовков conftest
$(obj)/conftest/headers.h: $(call NV_HEADER_PRESENCE_PART,$(NV_HEADER_PRESENCE_TESTS))
    @cat $^ > $@

# Очистка временных директорий
clean-dirs := $(obj)/conftest

# Санитарные проверки среды сборки и целевой системы/ядра
BUILD_SANITY_CHECKS = cc_sanity_check cc_version_check dom0_sanity_check xen_sanity_check preempt_rt_sanity_check vgpu_kvm_sanity_check module_symvers_sanity_check

.PHONY: $(BUILD_SANITY_CHECKS)

$(BUILD_SANITY_CHECKS):
    @$(NV_CONFTEST_CMD) $@ full_output

# Выполнение всех санитарных проверок перед генерацией заголовков conftest
$(NV_CONFTEST_HEADERS): | $(BUILD_SANITY_CHECKS)

# Генерация версии ядра
$(obj)/conftest/uts_release: NV_GENERATE_UTS_RELEASE
    @mkdir -p $(dir $@)
    @NV_UTS_RELEASE="// Kernel version: `$(NV_CONFTEST_CMD) compile_tests '
